// Code generated by jsonschema-projector; DO NOT EDIT.

package component

type Component interface {
	isComponent()
}

type ContainerChild interface {
	isContainerChild()
}

type Container struct {
	Child ContainerChild `json:"child,omitempty"`
}

type Image struct {
	URL string `json:"url"`
}

type Text struct {
	Value string `json:"value"`
}

func (Image) isComponent() {}

func (Image) isContainerChild() {}

func (Text) isComponent() {}

func (Text) isContainerChild() {}
