// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type Root struct {
	Values map[string]RootValuesValue `json:"values,omitzero"`
}

func (v *Root) UnmarshalJSON(data []byte) error {
	type Alias Root
	var aux struct {
		*Alias
		Values json.RawMessage `json:"values"`
	}
	aux.Alias = (*Alias)(v)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(aux.Values) != 0 {
		var raw map[string]json.RawMessage
		if err := json.Unmarshal(aux.Values, &raw); err != nil {
			return err
		}
		decoded := make(map[string]RootValuesValue)
		for key, item := range raw {
			value, err := UnmarshalRootValuesValue(item)
			if err != nil {
				return err
			}
			decoded[key] = value
		}
		v.Values = decoded
	}
	return nil
}

type StringValue string

type BooleanValue bool

type RootValuesValue interface {
	isRootValuesValue()
}

func (BooleanValue) isRootValuesValue() {}

func (StringValue) isRootValuesValue() {}

// UnmarshalRootValuesValue decodes one of the generated RootValuesValue variants.
func UnmarshalRootValuesValue(data []byte) (RootValuesValue, error) {
	var zero RootValuesValue

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case 't', 'f':
			var value BooleanValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			return zero, ErrUnknownVariant
		}
		break
	}
	return zero, ErrUnknownVariant
}

func UnmarshalRootValuesValueSlice(data []byte) ([]RootValuesValue, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]RootValuesValue, len(raw))
	for i, item := range raw {
		value, err := UnmarshalRootValuesValue(item)
		if err != nil {
			return nil, fmt.Errorf("RootValuesValue[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalRootValuesValueSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalRootValuesValueSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (RootValuesValue, error) {
	var zero RootValuesValue
	if validate == nil {
		return zero, errors.New("RootValuesValue schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("BooleanValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "BooleanValue"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "BooleanValue":
		var value BooleanValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalRootValuesValueValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalRootValuesValueValidated(data []byte, validate func([]byte) error) (RootValuesValue, error) {
	value, err := UnmarshalRootValuesValue(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
