// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type StringValue string

type BooleanValue bool

type Choice interface {
	isChoice()
}

type Container struct {
	Value ContainerValue `json:"value,omitzero"`
}

func (v *Container) UnmarshalJSON(data []byte) error {
	type Alias Container
	var aux struct {
		*Alias
		Value json.RawMessage `json:"value"`
	}
	aux.Alias = (*Alias)(v)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(aux.Value) != 0 {
		decoded, err := UnmarshalContainerValue(aux.Value)
		if err != nil {
			return err
		}
		v.Value = decoded
	}

	return nil
}

type NumberValue float64

type ContainerValue interface {
	isContainerValue()
}

func (BooleanValue) isChoice() {}

func (BooleanValue) isContainerValue() {}

func (NumberValue) isContainerValue() {}

func (StringValue) isChoice() {}

func (StringValue) isContainerValue() {}

// UnmarshalChoice decodes one of the generated Choice variants.
func UnmarshalChoice(data []byte) (Choice, error) {
	var zero Choice

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case 't', 'f':
			var value BooleanValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			return zero, ErrUnknownVariant
		}
		break
	}
	return zero, ErrUnknownVariant
}

func UnmarshalChoiceSlice(data []byte) ([]Choice, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]Choice, len(raw))
	for i, item := range raw {
		value, err := UnmarshalChoice(item)
		if err != nil {
			return nil, fmt.Errorf("Choice[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalChoiceSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalChoiceSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (Choice, error) {
	var zero Choice
	if validate == nil {
		return zero, errors.New("Choice schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("BooleanValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "BooleanValue"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "BooleanValue":
		var value BooleanValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalChoiceValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalChoiceValidated(data []byte, validate func([]byte) error) (Choice, error) {
	value, err := UnmarshalChoice(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}

// UnmarshalContainerValue decodes one of the generated ContainerValue variants.
func UnmarshalContainerValue(data []byte) (ContainerValue, error) {
	var zero ContainerValue

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case 't', 'f':
			var value BooleanValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case '-', '0', '1', '2', '3', '4', '5', '6', '7', '8', '9':
			var value NumberValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			return zero, ErrUnknownVariant
		}
		break
	}
	return zero, ErrUnknownVariant
}

func UnmarshalContainerValueSlice(data []byte) ([]ContainerValue, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]ContainerValue, len(raw))
	for i, item := range raw {
		value, err := UnmarshalContainerValue(item)
		if err != nil {
			return nil, fmt.Errorf("ContainerValue[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalContainerValueSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalContainerValueSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (ContainerValue, error) {
	var zero ContainerValue
	if validate == nil {
		return zero, errors.New("ContainerValue schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("BooleanValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "BooleanValue"
	}
	valid, err = validate("NumberValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "NumberValue"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "BooleanValue":
		var value BooleanValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "NumberValue":
		var value NumberValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalContainerValueValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalContainerValueValidated(data []byte, validate func([]byte) error) (ContainerValue, error) {
	value, err := UnmarshalContainerValue(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
