// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type Root struct {
	Value RootValue `json:"value,omitzero"`
}

func (v *Root) UnmarshalJSON(data []byte) error {
	type Alias Root
	var aux struct {
		*Alias
		Value json.RawMessage `json:"value"`
	}
	aux.Alias = (*Alias)(v)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(aux.Value) != 0 {
		decoded, err := UnmarshalRootValue(aux.Value)
		if err != nil {
			return err
		}
		v.Value = decoded
	}
	return nil
}

type StringValue string

type BooleanValue bool

type RootValue interface {
	isRootValue()
}

func (BooleanValue) isRootValue() {}

func (StringValue) isRootValue() {}

// UnmarshalRootValue decodes one of the generated RootValue variants.
func UnmarshalRootValue(data []byte) (RootValue, error) {
	var zero RootValue

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case 't', 'f':
			var value BooleanValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			return zero, ErrUnknownVariant
		}
		break
	}
	return zero, ErrUnknownVariant
}

func UnmarshalRootValueSlice(data []byte) ([]RootValue, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]RootValue, len(raw))
	for i, item := range raw {
		value, err := UnmarshalRootValue(item)
		if err != nil {
			return nil, fmt.Errorf("RootValue[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalRootValueSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalRootValueSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (RootValue, error) {
	var zero RootValue
	if validate == nil {
		return zero, errors.New("RootValue schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("BooleanValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "BooleanValue"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "BooleanValue":
		var value BooleanValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalRootValueValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalRootValueValidated(data []byte, validate func([]byte) error) (RootValue, error) {
	value, err := UnmarshalRootValue(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
