// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type StringValue string

type BooleanValue bool

type Value interface {
	isValue()
}

func (BooleanValue) isValue() {}

func (StringValue) isValue() {}

// UnmarshalValue decodes one of the generated Value variants.
func UnmarshalValue(data []byte) (Value, error) {
	var zero Value

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		case 't', 'f':
			var value BooleanValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			return zero, ErrUnknownVariant
		}
		break
	}
	return zero, ErrUnknownVariant
}

func UnmarshalValueSlice(data []byte) ([]Value, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]Value, len(raw))
	for i, item := range raw {
		value, err := UnmarshalValue(item)
		if err != nil {
			return nil, fmt.Errorf("Value[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalValueSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalValueSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (Value, error) {
	var zero Value
	if validate == nil {
		return zero, errors.New("Value schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("BooleanValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "BooleanValue"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "BooleanValue":
		var value BooleanValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalValueValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalValueValidated(data []byte, validate func([]byte) error) (Value, error) {
	value, err := UnmarshalValue(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
