// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type StringValue string

type Recursive interface {
	isRecursive()
}

type RecursiveObject struct {
	Next Recursive `json:"next"`
}

func (v *RecursiveObject) UnmarshalJSON(data []byte) error {
	type Alias RecursiveObject
	var aux struct {
		*Alias
		Next json.RawMessage `json:"next"`
	}
	aux.Alias = (*Alias)(v)
	if err := json.Unmarshal(data, &aux); err != nil {
		return err
	}
	if len(aux.Next) != 0 {
		decoded, err := UnmarshalRecursive(aux.Next)
		if err != nil {
			return err
		}
		v.Next = decoded
	}

	return nil
}

func (RecursiveObject) isRecursive() {}

func (StringValue) isRecursive() {}

// UnmarshalRecursive decodes one of the generated Recursive variants.
func UnmarshalRecursive(data []byte) (Recursive, error) {
	var zero Recursive

	for i := 0; i < len(data); i++ {
		if data[i] == ' ' || data[i] == '\n' || data[i] == '\r' || data[i] == '\t' {
			continue
		}
		switch data[i] {
		case '"':
			var value StringValue
			if err := json.Unmarshal(data, &value); err != nil {
				return zero, err
			}
			return value, nil
		default:
			break
		}
		break
	}
	var envelope map[string]json.RawMessage
	if err := json.Unmarshal(data, &envelope); err != nil {
		return zero, err
	}
	if hasJSONField(envelope, "next") {
		var value RecursiveObject
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

func UnmarshalRecursiveSlice(data []byte) ([]Recursive, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]Recursive, len(raw))
	for i, item := range raw {
		value, err := UnmarshalRecursive(item)
		if err != nil {
			return nil, fmt.Errorf("Recursive[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalRecursiveSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalRecursiveSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (Recursive, error) {
	var zero Recursive
	if validate == nil {
		return zero, errors.New("Recursive schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("StringValue", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "StringValue"
	}
	valid, err = validate("RecursiveObject", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "RecursiveObject"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "StringValue":
		var value StringValue
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "RecursiveObject":
		var value RecursiveObject
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// UnmarshalRecursiveValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalRecursiveValidated(data []byte, validate func([]byte) error) (Recursive, error) {
	value, err := UnmarshalRecursive(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
