// Code generated by jsonschema-projector; DO NOT EDIT.

package component

type Component interface {
	isComponent()
}

type Image struct {
	URL string `json:"url"`
}

type Text struct {
	Value string `json:"value"`
}

func (Image) isComponent() {}

func (Text) isComponent() {}
