// Code generated by jsonschema-projector; DO NOT EDIT.

package component

import (
	"encoding/json"
	"errors"
	"fmt"
	"sync"
)

var (
	ErrUnknownVariant   = errors.New("unknown union variant")
	ErrAmbiguousVariant = errors.New("ambiguous union variant")
)

func hasJSONField(value map[string]json.RawMessage, name string) bool {
	_, ok := value[name]
	return ok
}

func jsonTypeIs(raw json.RawMessage, want string) bool {
	for _, c := range raw {
		if c == ' ' || c == '\n' || c == '\r' || c == '\t' {
			continue
		}
		switch want {
		case "string":
			return c == '"'
		case "object":
			return c == '{'
		case "array":
			return c == '['
		case "boolean":
			return c == 't' || c == 'f'
		case "number":
			return c == '-' || (c >= '0' && c <= '9')
		case "null":
			return c == 'n'
		}
		return false
	}
	return false
}

type Component interface {
	isComponent()
}

type Image struct {
	URL string `json:"url"`
}

type Text struct {
	Value string `json:"value"`
}

func (Image) isComponent() {}

func (Text) isComponent() {}

// UnmarshalComponent decodes one of the generated Component variants.
func UnmarshalComponent(data []byte) (Component, error) {
	var zero Component
	if validate := lookupComponentSchemaValidator(); validate != nil {
		return UnmarshalComponentSchemaValidated(data, validate)
	}

	var envelope map[string]json.RawMessage
	if err := json.Unmarshal(data, &envelope); err != nil {
		return zero, err
	}
	matches := 0
	if hasJSONField(envelope, "value") && (!hasJSONField(envelope, "value") || jsonTypeIs(envelope["value"], "string")) {
		matches++
	}
	if hasJSONField(envelope, "url") && (!hasJSONField(envelope, "url") || jsonTypeIs(envelope["url"], "string")) {
		matches++
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	if hasJSONField(envelope, "value") && (!hasJSONField(envelope, "value") || jsonTypeIs(envelope["value"], "string")) {
		var value Text
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	if hasJSONField(envelope, "url") && (!hasJSONField(envelope, "url") || jsonTypeIs(envelope["url"], "string")) {
		var value Image
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

func UnmarshalComponentSlice(data []byte) ([]Component, error) {
	var raw []json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}
	values := make([]Component, len(raw))
	for i, item := range raw {
		value, err := UnmarshalComponent(item)
		if err != nil {
			return nil, fmt.Errorf("Component[%d]: %w", i, err)
		}
		values[i] = value
	}
	return values, nil
}

// UnmarshalComponentSchemaValidated dispatches by asking the application
// validator whether each candidate schema accepts data. The validator must
// implement the complete JSON Schema semantics for the candidate, including
// nested refs, allOf, anyOf, formats, and annotations relevant to the app.
// The bool result means "candidate matches"; operational errors are returned.
func UnmarshalComponentSchemaValidated(data []byte, validate func(string, []byte) (bool, error)) (Component, error) {
	var zero Component
	if validate == nil {
		return zero, errors.New("Component schema validator is nil")
	}
	matches := 0
	matched := ""
	var valid bool
	var err error
	valid, err = validate("Text", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "Text"
	}
	valid, err = validate("Image", data)
	if err != nil {
		return zero, err
	}
	if valid {
		matches++
		matched = "Image"
	}
	if matches != 1 {
		if matches > 1 {
			return zero, ErrAmbiguousVariant
		}
		return zero, ErrUnknownVariant
	}
	switch matched {
	case "Text":
		var value Text
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	case "Image":
		var value Image
		if err := json.Unmarshal(data, &value); err != nil {
			return zero, err
		}
		return value, nil
	}
	return zero, ErrUnknownVariant
}

// RegisterComponentSchemaValidator installs the application validator
// used by the default UnmarshalComponent path. It must perform complete JSON
// Schema validation for the candidate name it receives.
func RegisterComponentSchemaValidator(validate func(string, []byte) (bool, error)) {
	ComponentSchemaValidatorRegistry.Lock()
	defer ComponentSchemaValidatorRegistry.Unlock()
	ComponentSchemaValidatorRegistry.validate = validate
}

var ComponentSchemaValidatorRegistry = struct {
	sync.RWMutex
	validate func(string, []byte) (bool, error)
}{}

func lookupComponentSchemaValidator() func(string, []byte) (bool, error) {
	ComponentSchemaValidatorRegistry.RLock()
	defer ComponentSchemaValidatorRegistry.RUnlock()
	return ComponentSchemaValidatorRegistry.validate
}

// UnmarshalComponentValidated decodes a variant and delegates full JSON
// Schema validation to the application.
func UnmarshalComponentValidated(data []byte, validate func([]byte) error) (Component, error) {
	value, err := UnmarshalComponent(data)
	if err != nil {
		return value, err
	}
	if validate != nil {
		if err := validate(data); err != nil {
			return value, err
		}
	}
	return value, nil
}
