package generator

import (
	"bytes"
	"context"
	"encoding/json"
	"flag"
	"fmt"
	"go/format"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/satorunooshie/jsonschema-projector/projector"
)

var golden = flag.Bool("golden", false, "regenerate golden fixtures")

func FuzzGenerateGoNeverPanicsOnJSONObjects(f *testing.F) {
	for _, seed := range []string{
		`{"type":"object","properties":{"name":{"type":"string"}}}`,
		`{"allOf":[{"type":"object"},{"type":"object","required":["id"]}]}`,
		`{"anyOf":[{"type":"string"},{"type":"integer"}]}`,
		`{"$defs":{"Node":{"allOf":[{"$ref":"#/$defs/Node"}]}}}`,
	} {
		f.Add([]byte(seed))
	}

	f.Fuzz(func(t *testing.T, data []byte) {
		var schema map[string]any
		if err := json.Unmarshal(data, &schema); err != nil {
			t.Skip()
		}

		var stdout bytes.Buffer
		_, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "generated", Output: "-"}, schema, &stdout)
		if err != nil {
			t.Fatal(err)
		}
	})
}

func TestGenerateGoWritesNativeDTOs(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, "types.gen.go")
	schema := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
					"age":  map[string]any{"type": "integer"},
				},
				"required": []any{"name"},
			},
		},
	}

	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  outputPath,
	}
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if stdout.Len() != 0 {
		t.Fatalf("expected no stdout, got %q", stdout.String())
	}

	generated := readFile(t, outputPath)
	for _, want := range []string{
		"// Code generated by jsonschema-projector; DO NOT EDIT.",
		"package component",
		"type Person struct",
		"Age",
		"*int",
		"`json:\"age,omitzero\"`",
		"Name string `json:\"name\"`",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoMatchesGoldenAndCompiles(t *testing.T) {
	tests := []struct {
		name   string
		cfg    projector.GoGenerateConfig
		schema map[string]any
	}{
		{
			name: "native DTOs",
			cfg: projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			},
			schema: nativeDTOSchema(),
		},
		{
			name: "root oneOf",
			cfg: projector.GoGenerateConfig{
				Package:  "component",
				Output:   "-",
				RootType: "Component",
			},
			schema: componentUnionSchema(),
		},
		{
			name: "field oneOf",
			cfg: projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			},
			schema: fieldOneOfSchema(),
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, tt.cfg, tt.schema)
			assertGoldenFile(t, source, goldenFileName(t.Name(), ".golden.go"))
			assertGeneratedPackageCompiles(t, source)
		})
	}
}

func TestGenerateGoCanWriteToStdout(t *testing.T) {
	schema := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
				},
			},
		},
	}

	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if !strings.Contains(stdout.String(), "type Person struct") {
		t.Fatalf("expected generated source on stdout, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRepresentsRootOneOfAsClosedInterface(t *testing.T) {
	var stdout bytes.Buffer
	schema := componentUnionSchema()
	cfg := projector.GoGenerateConfig{
		Package:  "component",
		Output:   "-",
		RootType: "Component",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}

	generated := stdout.String()
	for _, want := range []string{
		"type Component interface {\n\tisComponent()\n}",
		"type Image struct",
		"type Text struct",
		"func (Image) isComponent() {}",
		"func (Text) isComponent() {}",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoKeepsRequiredPropertiesWithoutSchemas(t *testing.T) {
	var stdout bytes.Buffer
	schema := map[string]any{
		"$defs": map[string]any{
			"Event": map[string]any{
				"type":     "object",
				"required": []any{"kind"},
			},
		},
	}
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if !strings.Contains(stdout.String(), "Kind any `json:\"kind\"`") {
		t.Fatalf("expected required unconstrained field, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRepresentsFieldOneOfAsClosedInterface(t *testing.T) {
	var stdout bytes.Buffer
	schema := fieldOneOfSchema()
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}

	generated := stdout.String()
	for _, want := range []string{
		"type ContainerChild interface {\n\tisContainerChild()\n}",
		"Child ContainerChild `json:\"child,omitzero\"`",
		"func (Image) isContainerChild() {}",
		"func (Text) isContainerChild() {}",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoEmitsUnionDecodersAndPrimitiveWrappers(t *testing.T) {
	schema := map[string]any{
		"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "boolean"}},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Value"}, schema)
	assertGoldenFile(t, source, "primitive_anyof.golden.go")
	for _, want := range []string{
		"type Value interface",
		"type StringValue string",
		"type BooleanValue bool",
		"func UnmarshalValue(data []byte) (Value, error)",
		"func UnmarshalValueSlice(data []byte) ([]Value, error)",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated union source does not contain %q:\n%s", want, source)
		}
	}
	assertGeneratedPackageCompiles(t, source)
}

func TestGenerateGoConvertsPrimitiveTypeArrayToUnion(t *testing.T) {
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Value"}, map[string]any{
		"type": []any{"string", "number", "boolean", "null"},
	})
	for _, want := range []string{
		"type Value interface",
		"type StringValue string",
		"type NumberValue float64",
		"type BooleanValue bool",
		"type NullValue struct{}",
		"case 'n':",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated primitive union does not contain %q:\n%s", want, source)
		}
	}
}

func TestGenerateGoPromotesInlineObjectUnionVariant(t *testing.T) {
	schema := map[string]any{
		"type": "object",
		"properties": map[string]any{
			"value": map[string]any{"anyOf": []any{
				map[string]any{"type": "string"},
				map[string]any{"type": "object", "properties": map[string]any{"key": map[string]any{"type": "string"}}},
			}},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type ParentValueObject struct") && !strings.Contains(source, "type RootValueObject struct") {
		t.Fatalf("inline object union variant was not promoted to a named definition:\n%s", source)
	}
}

func TestGenerateGoEmitsDiscriminatorDispatch(t *testing.T) {
	schema := map[string]any{
		"oneOf": []any{map[string]any{"$ref": "#/$defs/Button"}, map[string]any{"$ref": "#/$defs/Text"}},
		"$defs": map[string]any{
			"Button": map[string]any{"type": "object", "properties": map[string]any{"component": map[string]any{"const": "Button"}}, "required": []any{"component"}},
			"Text":   map[string]any{"type": "object", "properties": map[string]any{"component": map[string]any{"const": "Text"}}, "required": []any{"component"}},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, schema)
	if !strings.Contains(source, "switch discriminator") || !strings.Contains(source, `case "Button":`) || !strings.Contains(source, `case "Text":`) {
		t.Fatalf("expected discriminator dispatch:\n%s", source)
	}
	assertGeneratedPackageCompiles(t, source)
}

func TestRefDiscriminatorUnknownValueAndNamedArrayDecoder(t *testing.T) {
	doc := map[string]any{
		"components": map[string]any{
			"schemas": map[string]any{
				"Foo": map[string]any{
					"type":       "object",
					"properties": map[string]any{"kind": map[string]any{"const": "foo"}},
					"required":   []any{"kind"},
				},
				"Bar": map[string]any{
					"type":       "object",
					"properties": map[string]any{"kind": map[string]any{"const": "bar"}},
					"required":   []any{"kind"},
				},
				"Choice": map[string]any{"oneOf": []any{
					map[string]any{"$ref": "#/components/schemas/Foo"},
					map[string]any{"$ref": "#/components/schemas/Bar"},
				}},
				"Items": map[string]any{
					"type": "array",
					"items": map[string]any{"oneOf": []any{
						map[string]any{"$ref": "#/components/schemas/Foo"},
						map[string]any{"$ref": "#/components/schemas/Bar"},
					}},
				},
			},
		},
	}
	projected, err := projector.ProjectSchema(context.Background(), doc, projector.ProjectConfig{
		IncludeDefinitions: []projector.DefinitionSource{{Pointer: "#/components/schemas"}},
		RewriteRefs:        []projector.RefRewrite{{From: "#/components/schemas/", To: "#/$defs/"}},
		Root:               &projector.RootSynthesis{Kind: "oneOf", From: "#/components/schemas", Names: []string{"Foo", "Bar"}},
		CheckRefs:          true,
	})
	if err != nil || projected.Diagnostics.HasErrors() {
		t.Fatalf("projection failed: %v %v", err, projected.Diagnostics)
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, projected.Schema)
	for _, want := range []string{
		"switch discriminator",
		"case \"foo\":",
		"case \"bar\":",
		"type Items []ItemsItem",
		"func (v *Items) UnmarshalJSON",
		"func UnmarshalItemsItem",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source is missing %q:\n%s", want, source)
		}
	}
	assertGeneratedPackageTests(t, source, `package component

import (
	"encoding/json"
	"errors"
	"testing"
)

func TestProjectedRefUnionRuntime(t *testing.T) {
	component, err := UnmarshalComponent([]byte("{\"kind\":\"foo\"}"))
	if err != nil || component == nil {
		t.Fatal(err)
	}
	if choice, err := UnmarshalChoice([]byte("{\"kind\":\"bar\"}")); err != nil || choice == nil {
		t.Fatalf("nested union decode failed: %v", err)
	}
	if _, err := UnmarshalComponent([]byte("{\"kind\":\"unknown\"}")); !errors.Is(err, ErrUnknownVariant) {
		t.Fatalf("got %v, want ErrUnknownVariant", err)
	}
	var items Items
	if err := json.Unmarshal([]byte("[{\"kind\":\"foo\"},{\"kind\":\"bar\"}]"), &items); err != nil {
		t.Fatal(err)
	}
	if len(items) != 2 || items[0] == nil || items[1] == nil {
		t.Fatalf("got %#v, want two decoded items", items)
	}
}
`)
}

func TestDuplicateRefDiscriminatorIsGenerationError(t *testing.T) {
	schema := map[string]any{
		"oneOf": []any{
			map[string]any{"$ref": "#/$defs/Foo"},
			map[string]any{"$ref": "#/$defs/Bar"},
		},
		"$defs": map[string]any{
			"Foo": map[string]any{"type": "object", "properties": map[string]any{"kind": map[string]any{"const": "same"}}, "required": []any{"kind"}},
			"Bar": map[string]any{"type": "object", "properties": map[string]any{"kind": map[string]any{"const": "same"}}, "required": []any{"kind"}},
		},
	}
	_, diagnostics, err := GenerateGoSource(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, schema)
	if err != nil {
		t.Fatal(err)
	}
	if !diagnostics.HasErrors() || !strings.Contains(fmt.Sprint(diagnostics), "discriminator values must be unique") {
		t.Fatalf("expected duplicate discriminator diagnostic, got %v", diagnostics)
	}
}

func TestNamedArrayAliasDecoderMatrix(t *testing.T) {
	schema := schemaWithDef("PrimitiveItems", map[string]any{
		"type": "array", "items": map[string]any{"type": "string"},
	})
	defs := schema["$defs"].(map[string]any)
	defs["ObjectItems"] = map[string]any{
		"type": "array", "items": map[string]any{
			"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}},
		},
	}
	defs["UnionItems"] = map[string]any{
		"type": "array", "items": map[string]any{"oneOf": []any{
			map[string]any{"$ref": "#/$defs/Foo"}, map[string]any{"$ref": "#/$defs/Bar"},
		}},
	}
	defs["NestedItems"] = map[string]any{
		"type": "array", "items": map[string]any{"$ref": "#/$defs/UnionItems"},
	}
	defs["Container"] = map[string]any{
		"type": "object", "properties": map[string]any{
			"items": map[string]any{"$ref": "#/$defs/UnionItems"},
		},
	}
	defs["Foo"] = map[string]any{"type": "object", "properties": map[string]any{"kind": map[string]any{"const": "foo"}}, "required": []any{"kind"}}
	defs["Bar"] = map[string]any{"type": "object", "properties": map[string]any{"kind": map[string]any{"const": "bar"}}, "required": []any{"kind"}}
	defs["AmbiguousItems"] = map[string]any{
		"type": "array", "items": map[string]any{"anyOf": []any{
			map[string]any{"type": "object", "properties": map[string]any{"x": map[string]any{"type": "string"}, "a": map[string]any{"type": "string"}}, "required": []any{"x"}},
			map[string]any{"type": "object", "properties": map[string]any{"x": map[string]any{"type": "string"}, "b": map[string]any{"type": "boolean"}}, "required": []any{"x"}},
		}},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	for _, name := range []string{"PrimitiveItems", "ObjectItems", "UnionItems", "NestedItems", "AmbiguousItems"} {
		if !strings.Contains(source, "func Unmarshal"+name+"(data []byte) ("+name+", error)") {
			t.Fatalf("missing named array decoder for %s:\n%s", name, source)
		}
	}
	assertGeneratedPackageTests(t, source, `package component

import (
	"encoding/json"
	"errors"
	"testing"
)

func TestNamedArrayAliasesRuntime(t *testing.T) {
	var primitive PrimitiveItems
	if err := json.Unmarshal([]byte("[]"), &primitive); err != nil || len(primitive) != 0 {
		t.Fatalf("empty primitive array: %v %#v", err, primitive)
	}
	if _, err := UnmarshalPrimitiveItems([]byte("[1]")); err == nil {
		t.Fatal("expected invalid primitive item error")
	}
	object, err := UnmarshalObjectItems([]byte("[{\"id\":\"one\"}]"))
	if err != nil || len(object) != 1 {
		t.Fatalf("object array: %v %#v", err, object)
	}
	union, err := UnmarshalUnionItems([]byte("[{\"kind\":\"foo\"},{\"kind\":\"bar\"}]"))
	if err != nil || len(union) != 2 {
		t.Fatalf("union array: %v %#v", err, union)
	}
	nested, err := UnmarshalNestedItems([]byte("[[{\"kind\":\"foo\"}]]"))
	if err != nil || len(nested) != 1 || len(nested[0]) != 1 {
		t.Fatalf("nested array: %v %#v", err, nested)
	}
	var container Container
	if err := json.Unmarshal([]byte("{\"items\":[{\"kind\":\"foo\"}]}"), &container); err != nil || container.Items == nil || len(*container.Items) != 1 {
		t.Fatalf("array field: %v %#v", err, container)
	}
	if _, err := UnmarshalUnionItems([]byte("[{\"kind\":\"unknown\"}]")); !errors.Is(err, ErrUnknownVariant) {
		t.Fatalf("got %v, want ErrUnknownVariant", err)
	}
	if _, err := UnmarshalAmbiguousItems([]byte("[{\"x\":\"same\"}]")); !errors.Is(err, ErrAmbiguousVariant) {
		t.Fatalf("got %v, want ErrAmbiguousVariant", err)
	}
}
`)
}

func TestGeneratedVariantRegistryIsConcurrentAndForwardCompatible(t *testing.T) {
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, map[string]any{
		"oneOf": []any{map[string]any{"$ref": "#/$defs/Button"}},
		"$defs": map[string]any{"Button": map[string]any{"type": "object", "properties": map[string]any{"component": map[string]any{"const": "Button"}}, "required": []any{"component"}}},
	})
	assertGeneratedPackageTestsGolden(t, source, "registry.golden_test.go")
}

func TestGeneratedUnionDecodersDecodeJSON(t *testing.T) {
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, componentUnionSchema())
	assertGeneratedPackageTestsGolden(t, source, "union_decode.golden_test.go")
}

func TestGeneratedAnyOfRejectsMultipleSchemaMatches(t *testing.T) {
	schema := componentUnionSchema()
	schema["anyOf"] = schema["oneOf"]
	delete(schema, "oneOf")
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, schema)
	assertGeneratedPackageTestsGolden(t, source, "union_decode.golden_test.go")
}

func TestGeneratedSchemaValidatedDispatchHonorsMatchCardinality(t *testing.T) {
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Component"}, componentUnionSchema())
	assertGeneratedPackageTestsGolden(t, source, "schema_validated_dispatch.golden_test.go")
}

func TestGeneratedSchemaValidationDispatchConfig(t *testing.T) {
	cfg := projector.GoGenerateConfig{
		Package:  "component",
		Output:   "-",
		RootType: "Component",
		Unions:   projector.UnionGenerateConfig{Dispatch: "schema-validation"},
	}
	source := generateGoSource(t, cfg, componentUnionSchema())
	assertGoldenFile(t, source, "schema_validation.golden.go")
	assertGeneratedPackageTestsGolden(t, source, "schema_dispatch.golden_test.go")
}

func TestGeneratedInterfaceFieldAndSliceDecode(t *testing.T) {
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, fieldOneOfSchema())
	assertGeneratedPackageTestsGolden(t, source, "interface_field.golden_test.go")
}

func FuzzGenerateGoUnionSource(f *testing.F) {
	f.Add([]byte(`{"oneOf":[{"type":"string"},{"type":"boolean"}]}`))
	f.Add([]byte(`{"anyOf":[{"type":"string"},{"type":"number"}]}`))
	f.Fuzz(func(t *testing.T, data []byte) {
		var schema map[string]any
		if json.Unmarshal(data, &schema) != nil {
			t.Skip()
		}
		_, _, err := GenerateGoSource(context.Background(), projector.GoGenerateConfig{Package: "generated", Output: "-", RootType: "Value"}, schema)
		if err != nil && err != context.Canceled {
			t.Fatal(err)
		}
	})
}

func TestGenerateGoSupportsInlinePrimitiveUnionMembers(t *testing.T) {
	var stdout bytes.Buffer
	schema := map[string]any{
		"$defs": map[string]any{
			"Choice": map[string]any{
				"oneOf": []any{
					map[string]any{"type": "string"},
				},
			},
		},
	}
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if !strings.Contains(stdout.String(), "type StringValue string") {
		t.Fatalf("expected primitive wrapper, got:\n%s", stdout.String())
	}
}

func TestGenerateGoReportsUnsupportedSchemas(t *testing.T) {
	tests := []struct {
		name        string
		schema      map[string]any
		wantPointer string
		wantMessage string
	}{
		{
			name: "incompatible allOf shapes",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{
					map[string]any{"type": "string"},
					map[string]any{"type": "integer"},
				},
			}),
			wantPointer: "#/$defs/Thing/allOf/1",
			wantMessage: "incompatible generated shapes",
		},
		{
			name:        "conditional",
			schema:      schemaWithDef("Thing", map[string]any{"if": map[string]any{"type": "object"}}),
			wantPointer: "#/$defs/Thing/if",
			wantMessage: "if is not supported",
		},
		{
			name: "multiple patternProperties",
			schema: schemaWithDef("Thing", map[string]any{"type": "object", "patternProperties": map[string]any{
				"^x-": map[string]any{"type": "string"},
				"^y-": map[string]any{"type": "string"},
			}}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "at most one uniform patternProperties",
		},
		{
			name:        "tuple items",
			schema:      schemaWithDef("Thing", map[string]any{"type": "array", "items": []any{map[string]any{"type": "string"}, map[string]any{"type": "integer"}}}),
			wantPointer: "#/$defs/Thing/items/1",
			wantMessage: "heterogeneous tuple arrays are not supported",
		},
		{
			name:        "prefixItems",
			schema:      schemaWithDef("Thing", map[string]any{"type": "array", "prefixItems": []any{map[string]any{"type": "string"}, map[string]any{"type": "integer"}}}),
			wantPointer: "#/$defs/Thing/prefixItems/1",
			wantMessage: "heterogeneous tuple arrays are not supported",
		},
		{
			name:        "external ref",
			schema:      schemaWithDef("Thing", map[string]any{"$ref": "other.schema.json#/$defs/Thing"}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "only local direct $defs refs are supported",
		},
		{
			name:        "nested ref",
			schema:      schemaWithDef("Thing", map[string]any{"$ref": "#/$defs/Outer/Inner"}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "only local direct $defs refs are supported",
		},
		{
			name:        "non string enum",
			schema:      schemaWithDef("Thing", map[string]any{"type": "string", "enum": []any{"open", 1}}),
			wantPointer: "#/$defs/Thing/enum/1",
			wantMessage: "enum values are not compatible",
		},
		{
			name:        "false schema",
			schema:      schemaWithDef("Thing", false),
			wantPointer: "#/$defs/Thing",
			wantMessage: "false schemas cannot be represented",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout bytes.Buffer
			cfg := projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			}

			diagnostics, err := GenerateGo(context.Background(), cfg, tt.schema, &stdout)
			if err != nil {
				t.Fatal(err)
			}
			assertUnsupportedDiagnostic(t, diagnostics, tt.wantPointer, tt.wantMessage)
			if stdout.Len() != 0 {
				t.Fatalf("expected no generated source, got:\n%s", stdout.String())
			}
		})
	}
}

func TestGenerateGoFlattensObjectAllOf(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"ComponentCommon": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"id": map[string]any{"type": "string"},
				},
				"required": []any{"id"},
			},
			"Text": map[string]any{
				"allOf": []any{
					map[string]any{"$ref": "#/$defs/ComponentCommon"},
					map[string]any{
						"type": "object",
						"properties": map[string]any{
							"component": map[string]any{"const": "Text"},
							"text":      map[string]any{"type": "string"},
						},
						"required": []any{"component", "text"},
					},
				},
			},
		},
	}

	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	for _, want := range []string{
		"type Text struct",
		"json:\"id\"`",
		"Component string `json:\"component\"`",
		"json:\"text\"`",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source does not contain %q:\n%s", want, source)
		}
	}

	emptyObject := schemaWithDef("EmptyComposition", map[string]any{
		"allOf": []any{map[string]any{}, map[string]any{"type": "object"}},
	})
	if source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, emptyObject); !strings.Contains(source, "type EmptyComposition map[string]any") {
		t.Fatalf("expected empty object composition to generate, got:\n%s", source)
	}
}

func TestGenerateGoFlattensCompatibleNonObjectAllOf(t *testing.T) {
	tests := []struct {
		name   string
		schema map[string]any
		want   string
	}{
		{
			name: "string",
			schema: schemaWithDef("Name", map[string]any{
				"allOf": []any{
					map[string]any{"type": "string", "minLength": 1},
					map[string]any{"type": "string", "maxLength": 100},
				},
			}),
			want: "type Name string",
		},
		{
			name: "array",
			schema: schemaWithDef("Names", map[string]any{
				"allOf": []any{
					map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					map[string]any{"type": "array", "minItems": 1},
				},
			}),
			want: "type Names []string",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema)
			if !strings.Contains(source, tt.want) {
				t.Fatalf("generated source does not contain %q:\n%s", tt.want, source)
			}
		})
	}
}

func TestGenerateGoCollapsesSameShapeAnyOf(t *testing.T) {
	schema := schemaWithDef("Name", map[string]any{
		"anyOf": []any{
			map[string]any{"type": "string", "minLength": 1},
			map[string]any{"type": "string", "maxLength": 100},
		},
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Name string") {
		t.Fatalf("expected same-shape anyOf to collapse to string, got:\n%s", source)
	}
}

func TestGenerateGoCollapsesAnyOfRefWithoutLosingReference(t *testing.T) {
	schema := map[string]any{
		"anyOf": []any{
			map[string]any{"$ref": "#/$defs/Name"},
			map[string]any{"$ref": "#/$defs/Name"},
		},
		"$defs": map[string]any{
			"Name": map[string]any{"type": "string"},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Name string") {
		t.Fatalf("expected anyOf refs to collapse to the referenced type, got:\n%s", source)
	}
}

func TestGenerateGoSupportsPrimitiveEnumConstants(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"StatusCode": map[string]any{"type": "integer", "enum": []any{200, 404}},
			"Enabled":    map[string]any{"type": "boolean", "enum": []any{true, false}},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	for _, want := range []string{
		"type StatusCode int",
		"StatusCodeValue1 StatusCode = 200",
		"StatusCodeValue2 StatusCode = 404",
		"type Enabled bool",
		"EnabledValue1 Enabled = true",
		"EnabledValue2 Enabled = false",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source does not contain %q:\n%s", want, source)
		}
	}
}

func TestGenerateGoSupportsUniformPatternProperties(t *testing.T) {
	schema := schemaWithDef("Labels", map[string]any{
		"type": "object",
		"patternProperties": map[string]any{
			"^[a-z]+$": map[string]any{"type": "string"},
		},
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Labels map[string]string") {
		t.Fatalf("expected uniform patternProperties map, got:\n%s", source)
	}
}

func TestGenerateGoSupportsHomogeneousTupleArrays(t *testing.T) {
	schema := schemaWithDef("Pair", map[string]any{
		"type": "array",
		"prefixItems": []any{
			map[string]any{"type": "string"},
			map[string]any{"type": "string"},
		},
		"items": false,
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Pair [2]string") {
		t.Fatalf("expected homogeneous tuple array, got:\n%s", source)
	}
}

func TestGenerateGoRejectsPrefixItemsWithSchemaItems(t *testing.T) {
	schema := schemaWithDef("Pair", map[string]any{
		"type": "array",
		"prefixItems": []any{
			map[string]any{"type": "string"},
		},
		"items": map[string]any{"type": "string"},
	})
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-"}, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	assertUnsupportedDiagnostic(t, diagnostics, "#/$defs/Pair/items", "prefixItems with schema-valued items")
	if stdout.Len() != 0 {
		t.Fatalf("expected no generated source, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRejectsUnsafeAllOfShapes(t *testing.T) {
	tests := []struct {
		name        string
		schema      map[string]any
		wantPointer string
		wantMessage string
	}{
		{
			name: "conflicting property",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{
					map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "string"}}},
					map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "integer"}}},
				},
			}),
			wantPointer: "#/$defs/Thing/allOf/1/properties/value",
			wantMessage: "defines property \"value\" more than once",
		},
		{
			name: "recursive composition",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{map[string]any{"$ref": "#/$defs/Thing"}},
			}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "recursive allOf composition",
		},
		{
			name: "reference with sibling keywords",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{map[string]any{
					"$ref": "#/$defs/Base",
					"type": "object",
				}},
			}),
			wantPointer: "#/$defs/Thing/allOf/0",
			wantMessage: "$ref with sibling keywords",
		},
		{
			name: "reference combined with allOf",
			schema: schemaWithDef("Thing", map[string]any{
				"$ref":  "#/$defs/Base",
				"allOf": []any{map[string]any{"type": "object"}},
			}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "$ref combined with allOf",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout bytes.Buffer
			diagnostics, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema, &stdout)
			if err != nil {
				t.Fatal(err)
			}
			assertUnsupportedDiagnostic(t, diagnostics, tt.wantPointer, tt.wantMessage)
			if stdout.Len() != 0 {
				t.Fatalf("expected no generated source, got:\n%s", stdout.String())
			}
		})
	}
}

func TestValidateGoConfigRequiresPackageAndOutput(t *testing.T) {
	diagnostics := ValidateGoConfig(&projector.GoGenerateConfig{})
	if !diagnostics.HasErrors() {
		t.Fatalf("expected diagnostics, got %v", diagnostics)
	}
}

func nativeDTOSchema() map[string]any {
	return map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
					"age":  map[string]any{"type": "integer"},
				},
				"required": []any{"name"},
			},
		},
	}
}

func componentUnionSchema() map[string]any {
	return map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"title":   "Component",
		"oneOf": []any{
			map[string]any{"$ref": "#/$defs/Text"},
			map[string]any{"$ref": "#/$defs/Image"},
		},
		"$defs": map[string]any{
			"Image": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"url": map[string]any{"type": "string"},
				},
				"required": []any{"url"},
			},
			"Text": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"value": map[string]any{"type": "string"},
				},
				"required": []any{"value"},
			},
		},
	}
}

func fieldOneOfSchema() map[string]any {
	schema := componentUnionSchema()
	defs := schema["$defs"].(map[string]any)
	defs["Container"] = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"child": map[string]any{
				"oneOf": []any{
					map[string]any{"$ref": "#/$defs/Text"},
					map[string]any{"$ref": "#/$defs/Image"},
				},
			},
		},
	}
	return schema
}

func schemaWithDef(name string, def any) map[string]any {
	return map[string]any{
		"$defs": map[string]any{
			name: def,
		},
	}
}

func generateGoSource(t *testing.T, cfg projector.GoGenerateConfig, schema map[string]any) string {
	t.Helper()

	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	return stdout.String()
}

func assertGoldenFile(t *testing.T, generated, path string) {
	t.Helper()

	goldenPath := filepath.Join("testdata", path)
	if *golden {
		if err := os.WriteFile(goldenPath, []byte(generated), 0o644); err != nil {
			t.Fatalf("update golden %s: %v", path, err)
		}
		return
	}
	want := readFile(t, goldenPath)
	formatted, err := format.Source([]byte(want))
	if err != nil {
		t.Fatalf("golden source %s is not valid Go: %v", path, err)
	}
	if normalizeNewlines(string(formatted)) != normalizeNewlines(want) {
		t.Fatalf("golden source %s is not gofmt-formatted", path)
	}
	if normalizeNewlines(generated) != normalizeNewlines(want) {
		t.Fatalf("generated Go source differs from %s at line %d\nwant: %s\ngot:  %s", path, firstDifferentLine(want, generated), lineAt(want, firstDifferentLine(want, generated)), lineAt(generated, firstDifferentLine(want, generated)))
	}
}

func goldenFileName(testName, suffix string) string {
	if slash := strings.LastIndexByte(testName, '/'); slash >= 0 {
		testName = testName[slash+1:]
	}
	var builder strings.Builder
	separator := false
	for _, r := range strings.ToLower(testName) {
		if (r >= 'a' && r <= 'z') || (r >= '0' && r <= '9') {
			separator = false
			builder.WriteRune(r)
			continue
		}
		if builder.Len() == 0 || separator {
			continue
		}
		builder.WriteByte('_')
		separator = true
	}
	return strings.TrimSuffix(builder.String(), "_") + suffix
}

func TestGoldenFileNameUsesSubtestLeaf(t *testing.T) {
	t.Parallel()

	cases := []struct {
		name string
		want string
	}{
		{name: "TestGenerate/root oneOf", want: "root_oneof.golden.go"},
		{name: "TestGenerate/native DTOs", want: "native_dtos.golden.go"},
		{name: "TestGenerate/primitive.anyOf", want: "primitive_anyof.golden.go"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			if got := goldenFileName(tc.name, ".golden.go"); got != tc.want {
				t.Fatalf("goldenFileName(%q) = %q, want %q", tc.name, got, tc.want)
			}
		})
	}
}

func assertGeneratedPackageCompiles(t *testing.T, source string) {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/generated\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "types.gen.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command("go", "test", "./...")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package does not compile: %v\n%s\nsource:\n%s", err, string(output), source)
	}
}

func assertGeneratedPackageTests(t *testing.T, source, testSource string) {
	t.Helper()
	dir := t.TempDir()
	for path, data := range map[string][]byte{
		"go.mod":        []byte("module example.com/generated\n\ngo 1.22\n"),
		"types.gen.go":  []byte(source),
		"types_test.go": []byte(testSource),
	} {
		if err := os.WriteFile(filepath.Join(dir, path), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command("go", "test", "./...")
	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated package tests failed: %v\n%s\nsource:\n%s", err, string(output), source)
	}
}

func assertGeneratedPackageTestsGolden(t *testing.T, source, golden string) {
	t.Helper()
	testSource := readFile(t, filepath.Join("testdata", golden))
	formatted, err := format.Source([]byte(testSource))
	if err != nil {
		t.Fatalf("golden generated test %s is not valid gofmt input: %v", golden, err)
	}
	if string(formatted) != testSource {
		t.Fatalf("golden generated test %s is not gofmt-formatted", golden)
	}
	dir := t.TempDir()
	for path, data := range map[string][]byte{
		"go.mod":        []byte("module example.com/generated\n\ngo 1.22\n"),
		"types.gen.go":  []byte(source),
		"types_test.go": []byte(testSource),
	} {
		if err := os.WriteFile(filepath.Join(dir, path), data, 0o644); err != nil {
			t.Fatal(err)
		}
	}
	cmd := exec.Command("go", "test", "./...")
	cmd.Dir = dir
	if output, err := cmd.CombinedOutput(); err != nil {
		t.Fatalf("generated package tests failed: %v\n%s\nsource:\n%s", err, string(output), source)
	}
}

func firstDifferentLine(want, got string) int {
	wantLines := strings.Split(normalizeNewlines(want), "\n")
	gotLines := strings.Split(normalizeNewlines(got), "\n")
	limit := min(len(wantLines), len(gotLines))
	for i := range limit {
		if wantLines[i] != gotLines[i] {
			return i + 1
		}
	}
	return limit + 1
}

func lineAt(source string, line int) string {
	lines := strings.Split(normalizeNewlines(source), "\n")
	if line < 1 || line > len(lines) {
		return "<missing>"
	}
	return strings.TrimSpace(lines[line-1])
}

func assertUnsupportedDiagnostic(t *testing.T, diagnostics projector.Diagnostics, pointer, message string) {
	t.Helper()

	for _, d := range diagnostics {
		if d.Code == projector.CodeUnsupportedSchema && d.Pointer == pointer && strings.Contains(d.Message, message) {
			return
		}
	}
	t.Fatalf("expected unsupported schema diagnostic at %s containing %q, got %v", pointer, message, diagnostics)
}

func TestUnionGenerationMatrix(t *testing.T) {
	cases := []struct {
		name      string
		schema    map[string]any
		root      string
		want      []string
		wantError bool
	}{
		{name: "primitive anyOf", schema: map[string]any{"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "boolean"}}}, root: "Value", want: []string{"type StringValue string", "type BooleanValue bool", "func UnmarshalValue"}},
		{name: "ambiguous number", schema: map[string]any{"anyOf": []any{map[string]any{"type": "integer"}, map[string]any{"type": "number"}}}, root: "Value", wantError: true},
		{name: "allOf object", schema: schemaWithDef("Value", map[string]any{"allOf": []any{map[string]any{"type": "object", "required": []any{"id"}}, map[string]any{"properties": map[string]any{"id": map[string]any{"type": "string"}}}}}), want: []string{"type Value struct", "ID string"}},
		{name: "recursive object", schema: map[string]any{"$defs": map[string]any{"Node": map[string]any{"type": "object", "properties": map[string]any{"next": map[string]any{"$ref": "#/$defs/Node"}}}}}, want: []string{"type Node struct", "Next *Node"}},
		{
			name: "nested allOf refs",
			schema: map[string]any{"$defs": map[string]any{
				"Base":  map[string]any{"type": "object", "properties": map[string]any{"id": map[string]any{"type": "string"}}, "required": []any{"id"}},
				"Value": map[string]any{"allOf": []any{map[string]any{"$ref": "#/$defs/Base"}, map[string]any{"type": "object", "properties": map[string]any{"label": map[string]any{"type": "string"}}, "required": []any{"label"}}}},
			}},
			want: []string{"type Value struct", "ID string", "Label string"},
		},
		{
			name: "recursive nested allOf",
			schema: schemaWithDef("Node", map[string]any{"allOf": []any{
				map[string]any{"type": "object", "properties": map[string]any{
					"value": map[string]any{"type": "string"},
					"next":  map[string]any{"$ref": "#/$defs/Node"},
				}, "required": []any{"value"}},
			}}),
			want: []string{"type Node struct", "Value string", "Next", "*Node"},
		},
		{
			name: "nested anyOf refs",
			schema: map[string]any{"$defs": map[string]any{
				"Choice": map[string]any{"anyOf": []any{map[string]any{"$ref": "#/$defs/Text"}, map[string]any{"$ref": "#/$defs/Image"}}},
				"Text":   map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "string"}}, "required": []any{"value"}},
				"Image":  map[string]any{"type": "object", "properties": map[string]any{"url": map[string]any{"type": "string"}}, "required": []any{"url"}},
			}},
			want: []string{"type Choice interface", "func UnmarshalChoice"},
		},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			source, diagnostics, err := GenerateGoSource(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-", RootType: tc.root}, tc.schema)
			if err != nil {
				t.Fatal(err)
			}
			if tc.wantError {
				if !diagnostics.HasErrors() {
					t.Fatal("expected generation error")
				}
				return
			}
			if diagnostics.HasErrors() {
				t.Fatalf("unexpected diagnostics: %v", diagnostics)
			}
			for _, want := range tc.want {
				if !strings.Contains(string(source), want) {
					t.Fatalf("missing %q in generated source:\n%s", want, source)
				}
			}
			assertGeneratedPackageCompiles(t, string(source))
		})
	}
}

func TestNestedUnionReferenceIsFlattenedAndReusable(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"DataBinding": map[string]any{"oneOf": []any{
				map[string]any{"type": "string"},
				map[string]any{"type": "object", "properties": map[string]any{"path": map[string]any{"type": "string"}}, "required": []any{"path"}},
			}},
			"Container": map[string]any{"type": "object", "properties": map[string]any{
				"value": map[string]any{"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"$ref": "#/$defs/DataBinding"}}},
			}},
		},
	}
	source, diagnostics, err := GenerateGoSource(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if err != nil || diagnostics.HasErrors() {
		t.Fatalf("nested union generation failed: %v %v", err, diagnostics)
	}
	text := string(source)
	if strings.Count(text, "type StringValue string") != 1 {
		t.Fatalf("string wrapper was duplicated:\n%s", text)
	}
	if !strings.Contains(text, "type DataBinding interface") || !strings.Contains(text, "type ContainerValue interface") {
		t.Fatalf("expected reusable nested unions:\n%s", text)
	}
	assertGeneratedPackageCompiles(t, text)
}

func TestSameTokenUnionUsesConstraintsAtDecodeTime(t *testing.T) {
	schema := map[string]any{"anyOf": []any{
		map[string]any{"type": "string", "pattern": "^[a-z]+$"},
		map[string]any{"type": "string", "format": "email"},
	}}
	source, diagnostics, err := GenerateGoSource(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-", RootType: "Value"}, schema)
	if err != nil || diagnostics.HasErrors() {
		t.Fatalf("constrained union generation failed: %v %v", err, diagnostics)
	}
	assertGoldenFile(t, string(source), "constrained_union.golden.go")
	assertGeneratedPackageCompiles(t, string(source))
}

func TestRecursiveAnyOfDecodeAndGolden(t *testing.T) {
	schema := recursiveAnyOfSchema()
	cfg := projector.GoGenerateConfig{Package: "component", Output: "-"}
	first := generateGoSource(t, cfg, schema)
	second := generateGoSource(t, cfg, schema)
	if first != second {
		t.Fatal("recursive anyOf generation is not deterministic")
	}
	assertGoldenFile(t, first, "recursive_anyof.golden.go")
	assertGeneratedPackageTests(t, first, `package component

import (
	"encoding/json"
	"errors"
	"testing"
)

func TestRecursiveAnyOfRuntime(t *testing.T) {
	cases := []struct {
		name string
		data []byte
		kind string
	}{
		{name: "leaf", data: []byte("\"leaf\""), kind: "string"},
		{name: "recursive object", data: []byte("{\"next\":\"leaf\"}"), kind: "object"},
	}
	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			value, err := UnmarshalRecursive(tc.data)
			if err != nil { t.Fatal(err) }
			switch tc.kind {
			case "string":
				if _, ok := value.(StringValue); !ok { t.Fatalf("got %T, want StringValue", value) }
			case "object":
				object, ok := value.(RecursiveObject)
				if !ok || object.Next == nil { t.Fatalf("got %#v, want recursive object", value) }
				if _, ok := object.Next.(StringValue); !ok { t.Fatalf("got %T, want StringValue", object.Next) }
			}
		})
	}

	if _, err := UnmarshalRecursive([]byte("{\"next\":{}}")); !errors.Is(err, ErrUnknownVariant) {
		t.Fatalf("got %v, want unknown variant", err)
	}
	var roundTrip RecursiveObject
	if err := json.Unmarshal([]byte("{\"next\":\"leaf\"}"), &roundTrip); err != nil { t.Fatal(err) }
}

`)
}

func TestRecursiveAnyOfSelfReferenceIsAFixedPoint(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"Value": map[string]any{"anyOf": []any{
				map[string]any{"type": "string"},
				map[string]any{"$ref": "#/$defs/Value"},
			}},
		},
		"$ref": "#/$defs/Value",
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Value string") {
		t.Fatalf("recursive anyOf self-reference was not normalized to its fixed point:\n%s", source)
	}
	if strings.Contains(source, "func (Value) isValue()") {
		t.Fatalf("recursive union generated an invalid self-interface variant:\n%s", source)
	}
}

func recursiveAnyOfSchema() map[string]any {
	return map[string]any{
		"$defs": map[string]any{
			"Recursive": map[string]any{"anyOf": []any{
				map[string]any{"type": "string"},
				map[string]any{
					"type":       "object",
					"properties": map[string]any{"next": map[string]any{"$ref": "#/$defs/Recursive"}},
					"required":   []any{"next"},
				},
			}},
		},
		"$ref": "#/$defs/Recursive",
	}
}

func TestUnionContainerGenerationMatrix(t *testing.T) {
	union := func() map[string]any {
		return map[string]any{"anyOf": []any{
			map[string]any{"type": "string"},
			map[string]any{"type": "boolean"},
		}}
	}
	tests := []struct {
		name   string
		schema map[string]any
		golden string
	}{
		{
			name: "pointer field",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"value": union(),
			}}),
			golden: "pointer_union.golden.go",
		},
		{
			name: "slice element",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"values": map[string]any{"type": "array", "items": union()},
			}}),
			golden: "slice_union.golden.go",
		},
		{
			name: "map value",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"values": map[string]any{"type": "object", "additionalProperties": union()},
			}}),
			golden: "map_union.golden.go",
		},
		{
			name: "union reference inside union",
			schema: map[string]any{
				"$defs": map[string]any{
					"Choice": map[string]any{"oneOf": []any{
						map[string]any{"type": "string"},
						map[string]any{"type": "boolean"},
					}},
					"Container": map[string]any{"type": "object", "properties": map[string]any{
						"value": map[string]any{"anyOf": []any{
							map[string]any{"$ref": "#/$defs/Choice"},
							map[string]any{"type": "number"},
						}},
					}},
				},
			},
			golden: "nested_union_ref.golden.go",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema)
			assertGoldenFile(t, source, tt.golden)
			assertGeneratedPackageCompiles(t, source)
		})
	}
}

func TestGeneratedUnionContainersDecode(t *testing.T) {
	union := func() map[string]any {
		return map[string]any{"anyOf": []any{
			map[string]any{"type": "string"},
			map[string]any{"type": "boolean"},
		}}
	}
	tests := []struct {
		name       string
		schema     map[string]any
		assertions string
	}{
		{
			name: "field",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"value": union(),
			}}),
			assertions: `
	var value Root
	if err := json.Unmarshal([]byte("{\"value\":\"x\"}"), &value); err != nil { t.Fatal(err) }
	if _, ok := value.Value.(StringValue); !ok { t.Fatalf("got %T, want StringValue", value.Value) }
`,
		},
		{
			name: "slice",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"values": map[string]any{"type": "array", "items": union()},
			}}),
			assertions: `
	var value Root
	if err := json.Unmarshal([]byte("{\"values\":[\"x\",true]}"), &value); err != nil { t.Fatal(err) }
	if len(value.Values) != 2 { t.Fatalf("got %d values, want 2", len(value.Values)) }
	if _, ok := value.Values[0].(StringValue); !ok { t.Fatalf("got %T, want StringValue", value.Values[0]) }
	if _, ok := value.Values[1].(BooleanValue); !ok { t.Fatalf("got %T, want BooleanValue", value.Values[1]) }
`,
		},
		{
			name: "map",
			schema: schemaWithDef("Root", map[string]any{"type": "object", "properties": map[string]any{
				"values": map[string]any{"type": "object", "additionalProperties": union()},
			}}),
			assertions: `
	var value Root
	if err := json.Unmarshal([]byte("{\"values\":{\"a\":\"x\",\"b\":true}}"), &value); err != nil { t.Fatal(err) }
	if _, ok := value.Values["a"].(StringValue); !ok { t.Fatalf("got %T, want StringValue", value.Values["a"]) }
	if _, ok := value.Values["b"].(BooleanValue); !ok { t.Fatalf("got %T, want BooleanValue", value.Values["b"]) }
`,
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema)
			testSource := "package component\n\nimport (\n\t\"encoding/json\"\n\t\"testing\"\n)\n\nfunc TestGeneratedContainerRuntime(t *testing.T) {" + tt.assertions + "}\n"
			assertGeneratedPackageTests(t, source, testSource)
		})
	}
}

func TestGeneratedStructWithMultipleUnionFieldsDecodesOnce(t *testing.T) {
	union := func() map[string]any {
		return map[string]any{"anyOf": []any{
			map[string]any{"type": "string"},
			map[string]any{"type": "boolean"},
		}}
	}
	schema := schemaWithDef("MultipleUnions", map[string]any{
		"type": "object",
		"properties": map[string]any{
			"first":  union(),
			"second": map[string]any{"type": "array", "items": union()},
			"third":  map[string]any{"type": "object", "additionalProperties": union()},
		},
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if got := strings.Count(source, "func (v *MultipleUnions) UnmarshalJSON"); got != 1 {
		t.Fatalf("generated %d UnmarshalJSON methods for MultipleUnions, want 1:\n%s", got, source)
	}
	assertGeneratedPackageTests(t, source, `package component

import (
	"encoding/json"
	"reflect"
	"testing"
)

func TestMultipleUnionFieldsRuntime(t *testing.T) {
	var value MultipleUnions
	if err := json.Unmarshal([]byte("{\"first\":\"one\",\"second\":[true,\"two\"],\"third\":{\"a\":\"three\",\"b\":false}}"), &value); err != nil {
		t.Fatal(err)
	}
	if reflect.TypeOf(value.First).Name() != "StringValue" {
		t.Fatalf("first decoded as %T", value.First)
	}
	if len(value.Second) != 2 || reflect.TypeOf(value.Second[0]).Name() != "BooleanValue" || reflect.TypeOf(value.Second[1]).Name() != "StringValue" {
		t.Fatalf("second decoded as %#v", value.Second)
	}
	if len(value.Third) != 2 || reflect.TypeOf(value.Third["a"]).Name() != "StringValue" || reflect.TypeOf(value.Third["b"]).Name() != "BooleanValue" {
		t.Fatalf("third decoded as %#v", value.Third)
	}
}
`)
}

func TestEmbeddedTemplatesAreComplete(t *testing.T) {
	t.Parallel()

	for _, name := range []string{
		"alias",
		"array-unmarshal",
		"constants",
		"preamble",
		"source",
		"struct",
		"struct-unmarshal",
		"struct-unmarshal-map",
		"union",
		"union-case",
		"union-decoder",
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if source, err := embeddedTemplate(name); err != nil || strings.TrimSpace(source) == "" {
				t.Fatalf("embedded template %q is unavailable or empty: %v", name, err)
			}
		})
	}
}

func normalizeNewlines(value string) string {
	return strings.ReplaceAll(value, "\r\n", "\n")
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
