package generator

import (
	"bytes"
	"context"
	"encoding/json"
	"os"
	"os/exec"
	"path/filepath"
	"strings"
	"testing"

	"github.com/satorunooshie/jsonschema-projector/projector"
)

func FuzzGenerateGoNeverPanicsOnJSONObjects(f *testing.F) {
	for _, seed := range []string{
		`{"type":"object","properties":{"name":{"type":"string"}}}`,
		`{"allOf":[{"type":"object"},{"type":"object","required":["id"]}]}`,
		`{"anyOf":[{"type":"string"},{"type":"integer"}]}`,
		`{"$defs":{"Node":{"allOf":[{"$ref":"#/$defs/Node"}]}}}`,
	} {
		f.Add([]byte(seed))
	}

	f.Fuzz(func(t *testing.T, data []byte) {
		var schema map[string]any
		if err := json.Unmarshal(data, &schema); err != nil {
			t.Skip()
		}

		var stdout bytes.Buffer
		_, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "generated", Output: "-"}, schema, &stdout)
		if err != nil {
			t.Fatal(err)
		}
	})
}

func TestGenerateGoWritesNativeDTOs(t *testing.T) {
	dir := t.TempDir()
	outputPath := filepath.Join(dir, "types.gen.go")
	schema := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
					"age":  map[string]any{"type": "integer"},
				},
				"required": []any{"name"},
			},
		},
	}

	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  outputPath,
	}
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if stdout.Len() != 0 {
		t.Fatalf("expected no stdout, got %q", stdout.String())
	}

	generated := readFile(t, outputPath)
	for _, want := range []string{
		"// Code generated by jsonschema-projector; DO NOT EDIT.",
		"package component",
		"type Person struct",
		"Age",
		"*int",
		"`json:\"age,omitempty\"`",
		"Name string `json:\"name\"`",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoMatchesGoldenAndCompiles(t *testing.T) {
	tests := []struct {
		name   string
		cfg    projector.GoGenerateConfig
		schema map[string]any
		golden string
	}{
		{
			name: "native DTOs",
			cfg: projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			},
			schema: nativeDTOSchema(),
			golden: "native_dtos.golden.go",
		},
		{
			name: "root oneOf",
			cfg: projector.GoGenerateConfig{
				Package:  "component",
				Output:   "-",
				RootType: "Component",
			},
			schema: componentUnionSchema(),
			golden: "root_oneof.golden.go",
		},
		{
			name: "field oneOf",
			cfg: projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			},
			schema: fieldOneOfSchema(),
			golden: "field_oneof.golden.go",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, tt.cfg, tt.schema)
			assertGolden(t, source, tt.golden)
			assertGeneratedPackageCompiles(t, source)
		})
	}
}

func TestGenerateGoCanWriteToStdout(t *testing.T) {
	schema := map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
				},
			},
		},
	}

	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if !strings.Contains(stdout.String(), "type Person struct") {
		t.Fatalf("expected generated source on stdout, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRepresentsRootOneOfAsClosedInterface(t *testing.T) {
	var stdout bytes.Buffer
	schema := componentUnionSchema()
	cfg := projector.GoGenerateConfig{
		Package:  "component",
		Output:   "-",
		RootType: "Component",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}

	generated := stdout.String()
	for _, want := range []string{
		"type Component interface {\n\tisComponent()\n}",
		"type Image struct",
		"type Text struct",
		"func (Image) isComponent() {}",
		"func (Text) isComponent() {}",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoKeepsRequiredPropertiesWithoutSchemas(t *testing.T) {
	var stdout bytes.Buffer
	schema := map[string]any{
		"$defs": map[string]any{
			"Event": map[string]any{
				"type":     "object",
				"required": []any{"kind"},
			},
		},
	}
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	if !strings.Contains(stdout.String(), "Kind any `json:\"kind\"`") {
		t.Fatalf("expected required unconstrained field, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRepresentsFieldOneOfAsClosedInterface(t *testing.T) {
	var stdout bytes.Buffer
	schema := fieldOneOfSchema()
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}

	generated := stdout.String()
	for _, want := range []string{
		"type ContainerChild interface {\n\tisContainerChild()\n}",
		"Child ContainerChild `json:\"child,omitempty\"`",
		"func (Image) isContainerChild() {}",
		"func (Text) isContainerChild() {}",
	} {
		if !strings.Contains(generated, want) {
			t.Fatalf("generated Go source does not contain %q:\n%s", want, generated)
		}
	}
}

func TestGenerateGoRejectsUnsupportedOneOfMembers(t *testing.T) {
	var stdout bytes.Buffer
	schema := map[string]any{
		"$defs": map[string]any{
			"Choice": map[string]any{
				"oneOf": []any{
					map[string]any{"type": "string"},
				},
			},
		},
	}
	cfg := projector.GoGenerateConfig{
		Package: "component",
		Output:  "-",
	}

	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if !diagnostics.HasErrors() {
		t.Fatalf("expected diagnostics, got %v", diagnostics)
	}
	if stdout.Len() != 0 {
		t.Fatalf("expected no generated source, got:\n%s", stdout.String())
	}
}

func TestGenerateGoReportsUnsupportedSchemas(t *testing.T) {
	tests := []struct {
		name        string
		schema      map[string]any
		wantPointer string
		wantMessage string
	}{
		{
			name: "incompatible allOf shapes",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{
					map[string]any{"type": "string"},
					map[string]any{"type": "integer"},
				},
			}),
			wantPointer: "#/$defs/Thing/allOf/1",
			wantMessage: "incompatible generated shapes",
		},
		{
			name: "heterogeneous anyOf",
			schema: schemaWithDef("Thing", map[string]any{
				"anyOf": []any{map[string]any{"type": "string"}, map[string]any{"type": "integer"}},
			}),
			wantPointer: "#/$defs/Thing/anyOf/1",
			wantMessage: "single representable DTO shape",
		},
		{
			name:        "conditional",
			schema:      schemaWithDef("Thing", map[string]any{"if": map[string]any{"type": "object"}}),
			wantPointer: "#/$defs/Thing/if",
			wantMessage: "if is not supported",
		},
		{
			name: "multiple patternProperties",
			schema: schemaWithDef("Thing", map[string]any{"type": "object", "patternProperties": map[string]any{
				"^x-": map[string]any{"type": "string"},
				"^y-": map[string]any{"type": "string"},
			}}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "at most one uniform patternProperties",
		},
		{
			name:        "tuple items",
			schema:      schemaWithDef("Thing", map[string]any{"type": "array", "items": []any{map[string]any{"type": "string"}, map[string]any{"type": "integer"}}}),
			wantPointer: "#/$defs/Thing/items/1",
			wantMessage: "heterogeneous tuple arrays are not supported",
		},
		{
			name:        "prefixItems",
			schema:      schemaWithDef("Thing", map[string]any{"type": "array", "prefixItems": []any{map[string]any{"type": "string"}, map[string]any{"type": "integer"}}}),
			wantPointer: "#/$defs/Thing/prefixItems/1",
			wantMessage: "heterogeneous tuple arrays are not supported",
		},
		{
			name:        "external ref",
			schema:      schemaWithDef("Thing", map[string]any{"$ref": "other.schema.json#/$defs/Thing"}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "only local direct $defs refs are supported",
		},
		{
			name:        "nested ref",
			schema:      schemaWithDef("Thing", map[string]any{"$ref": "#/$defs/Outer/Inner"}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "only local direct $defs refs are supported",
		},
		{
			name: "inline oneOf member",
			schema: schemaWithDef("Thing", map[string]any{
				"oneOf": []any{
					map[string]any{"type": "string"},
				},
			}),
			wantPointer: "#/$defs/Thing/oneOf/0",
			wantMessage: "native oneOf support requires every member to be a $ref",
		},
		{
			name:        "non string enum",
			schema:      schemaWithDef("Thing", map[string]any{"type": "string", "enum": []any{"open", 1}}),
			wantPointer: "#/$defs/Thing/enum/1",
			wantMessage: "enum values are not compatible",
		},
		{
			name:        "multiple non-null types",
			schema:      schemaWithDef("Thing", map[string]any{"type": []any{"string", "integer"}}),
			wantPointer: "#/$defs/Thing/type",
			wantMessage: "multiple non-null JSON types are not supported",
		},
		{
			name:        "false schema",
			schema:      schemaWithDef("Thing", false),
			wantPointer: "#/$defs/Thing",
			wantMessage: "false schemas cannot be represented",
		},
		{
			name:        "null only",
			schema:      schemaWithDef("Thing", map[string]any{"type": []any{"null"}}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "null-only schemas cannot be represented",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout bytes.Buffer
			cfg := projector.GoGenerateConfig{
				Package: "component",
				Output:  "-",
			}

			diagnostics, err := GenerateGo(context.Background(), cfg, tt.schema, &stdout)
			if err != nil {
				t.Fatal(err)
			}
			assertUnsupportedDiagnostic(t, diagnostics, tt.wantPointer, tt.wantMessage)
			if stdout.Len() != 0 {
				t.Fatalf("expected no generated source, got:\n%s", stdout.String())
			}
		})
	}
}

func TestGenerateGoFlattensObjectAllOf(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"ComponentCommon": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"id": map[string]any{"type": "string"},
				},
				"required": []any{"id"},
			},
			"Text": map[string]any{
				"allOf": []any{
					map[string]any{"$ref": "#/$defs/ComponentCommon"},
					map[string]any{
						"type": "object",
						"properties": map[string]any{
							"component": map[string]any{"const": "Text"},
							"text":      map[string]any{"type": "string"},
						},
						"required": []any{"component", "text"},
					},
				},
			},
		},
	}

	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	for _, want := range []string{
		"type Text struct",
		"json:\"id\"`",
		"Component string `json:\"component\"`",
		"json:\"text\"`",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source does not contain %q:\n%s", want, source)
		}
	}

	emptyObject := schemaWithDef("EmptyComposition", map[string]any{
		"allOf": []any{map[string]any{}, map[string]any{"type": "object"}},
	})
	if source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, emptyObject); !strings.Contains(source, "type EmptyComposition map[string]any") {
		t.Fatalf("expected empty object composition to generate, got:\n%s", source)
	}
}

func TestGenerateGoFlattensCompatibleNonObjectAllOf(t *testing.T) {
	tests := []struct {
		name   string
		schema map[string]any
		want   string
	}{
		{
			name: "string",
			schema: schemaWithDef("Name", map[string]any{
				"allOf": []any{
					map[string]any{"type": "string", "minLength": 1},
					map[string]any{"type": "string", "maxLength": 100},
				},
			}),
			want: "type Name string",
		},
		{
			name: "array",
			schema: schemaWithDef("Names", map[string]any{
				"allOf": []any{
					map[string]any{"type": "array", "items": map[string]any{"type": "string"}},
					map[string]any{"type": "array", "minItems": 1},
				},
			}),
			want: "type Names []string",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema)
			if !strings.Contains(source, tt.want) {
				t.Fatalf("generated source does not contain %q:\n%s", tt.want, source)
			}
		})
	}
}

func TestGenerateGoCollapsesSameShapeAnyOf(t *testing.T) {
	schema := schemaWithDef("Name", map[string]any{
		"anyOf": []any{
			map[string]any{"type": "string", "minLength": 1},
			map[string]any{"type": "string", "maxLength": 100},
		},
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Name string") {
		t.Fatalf("expected same-shape anyOf to collapse to string, got:\n%s", source)
	}
}

func TestGenerateGoCollapsesAnyOfRefWithoutLosingReference(t *testing.T) {
	schema := map[string]any{
		"anyOf": []any{
			map[string]any{"$ref": "#/$defs/Name"},
			map[string]any{"$ref": "#/$defs/Name"},
		},
		"$defs": map[string]any{
			"Name": map[string]any{"type": "string"},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Name string") {
		t.Fatalf("expected anyOf refs to collapse to the referenced type, got:\n%s", source)
	}
}

func TestGenerateGoSupportsPrimitiveEnumConstants(t *testing.T) {
	schema := map[string]any{
		"$defs": map[string]any{
			"StatusCode": map[string]any{"type": "integer", "enum": []any{200, 404}},
			"Enabled":    map[string]any{"type": "boolean", "enum": []any{true, false}},
		},
	}
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	for _, want := range []string{
		"type StatusCode int",
		"StatusCodeValue1 StatusCode = 200",
		"StatusCodeValue2 StatusCode = 404",
		"type Enabled bool",
		"EnabledValue1 Enabled = true",
		"EnabledValue2 Enabled = false",
	} {
		if !strings.Contains(source, want) {
			t.Fatalf("generated source does not contain %q:\n%s", want, source)
		}
	}
}

func TestGenerateGoSupportsUniformPatternProperties(t *testing.T) {
	schema := schemaWithDef("Labels", map[string]any{
		"type": "object",
		"patternProperties": map[string]any{
			"^[a-z]+$": map[string]any{"type": "string"},
		},
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Labels map[string]string") {
		t.Fatalf("expected uniform patternProperties map, got:\n%s", source)
	}
}

func TestGenerateGoSupportsHomogeneousTupleArrays(t *testing.T) {
	schema := schemaWithDef("Pair", map[string]any{
		"type": "array",
		"prefixItems": []any{
			map[string]any{"type": "string"},
			map[string]any{"type": "string"},
		},
		"items": false,
	})
	source := generateGoSource(t, projector.GoGenerateConfig{Package: "component", Output: "-"}, schema)
	if !strings.Contains(source, "type Pair [2]string") {
		t.Fatalf("expected homogeneous tuple array, got:\n%s", source)
	}
}

func TestGenerateGoRejectsPrefixItemsWithSchemaItems(t *testing.T) {
	schema := schemaWithDef("Pair", map[string]any{
		"type": "array",
		"prefixItems": []any{
			map[string]any{"type": "string"},
		},
		"items": map[string]any{"type": "string"},
	})
	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-"}, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	assertUnsupportedDiagnostic(t, diagnostics, "#/$defs/Pair/items", "prefixItems with schema-valued items")
	if stdout.Len() != 0 {
		t.Fatalf("expected no generated source, got:\n%s", stdout.String())
	}
}

func TestGenerateGoRejectsUnsafeAllOfShapes(t *testing.T) {
	tests := []struct {
		name        string
		schema      map[string]any
		wantPointer string
		wantMessage string
	}{
		{
			name: "conflicting property",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{
					map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "string"}}},
					map[string]any{"type": "object", "properties": map[string]any{"value": map[string]any{"type": "integer"}}},
				},
			}),
			wantPointer: "#/$defs/Thing/allOf/1/properties/value",
			wantMessage: "defines property \"value\" more than once",
		},
		{
			name: "recursive composition",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{map[string]any{"$ref": "#/$defs/Thing"}},
			}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "recursive allOf composition",
		},
		{
			name: "reference with sibling keywords",
			schema: schemaWithDef("Thing", map[string]any{
				"allOf": []any{map[string]any{
					"$ref": "#/$defs/Base",
					"type": "object",
				}},
			}),
			wantPointer: "#/$defs/Thing/allOf/0",
			wantMessage: "$ref with sibling keywords",
		},
		{
			name: "reference combined with allOf",
			schema: schemaWithDef("Thing", map[string]any{
				"$ref":  "#/$defs/Base",
				"allOf": []any{map[string]any{"type": "object"}},
			}),
			wantPointer: "#/$defs/Thing",
			wantMessage: "$ref combined with allOf",
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			var stdout bytes.Buffer
			diagnostics, err := GenerateGo(context.Background(), projector.GoGenerateConfig{Package: "component", Output: "-"}, tt.schema, &stdout)
			if err != nil {
				t.Fatal(err)
			}
			assertUnsupportedDiagnostic(t, diagnostics, tt.wantPointer, tt.wantMessage)
			if stdout.Len() != 0 {
				t.Fatalf("expected no generated source, got:\n%s", stdout.String())
			}
		})
	}
}

func TestValidateGoConfigRequiresPackageAndOutput(t *testing.T) {
	diagnostics := ValidateGoConfig(&projector.GoGenerateConfig{})
	if !diagnostics.HasErrors() {
		t.Fatalf("expected diagnostics, got %v", diagnostics)
	}
}

func nativeDTOSchema() map[string]any {
	return map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"$defs": map[string]any{
			"Person": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"name": map[string]any{"type": "string"},
					"age":  map[string]any{"type": "integer"},
				},
				"required": []any{"name"},
			},
		},
	}
}

func componentUnionSchema() map[string]any {
	return map[string]any{
		"$schema": "https://json-schema.org/draft/2020-12/schema",
		"title":   "Component",
		"oneOf": []any{
			map[string]any{"$ref": "#/$defs/Text"},
			map[string]any{"$ref": "#/$defs/Image"},
		},
		"$defs": map[string]any{
			"Image": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"url": map[string]any{"type": "string"},
				},
				"required": []any{"url"},
			},
			"Text": map[string]any{
				"type": "object",
				"properties": map[string]any{
					"value": map[string]any{"type": "string"},
				},
				"required": []any{"value"},
			},
		},
	}
}

func fieldOneOfSchema() map[string]any {
	schema := componentUnionSchema()
	defs := schema["$defs"].(map[string]any)
	defs["Container"] = map[string]any{
		"type": "object",
		"properties": map[string]any{
			"child": map[string]any{
				"oneOf": []any{
					map[string]any{"$ref": "#/$defs/Text"},
					map[string]any{"$ref": "#/$defs/Image"},
				},
			},
		},
	}
	return schema
}

func schemaWithDef(name string, def any) map[string]any {
	return map[string]any{
		"$defs": map[string]any{
			name: def,
		},
	}
}

func generateGoSource(t *testing.T, cfg projector.GoGenerateConfig, schema map[string]any) string {
	t.Helper()

	var stdout bytes.Buffer
	diagnostics, err := GenerateGo(context.Background(), cfg, schema, &stdout)
	if err != nil {
		t.Fatal(err)
	}
	if diagnostics.HasErrors() {
		t.Fatalf("unexpected diagnostics: %v", diagnostics)
	}
	return stdout.String()
}

func assertGolden(t *testing.T, generated, path string) {
	t.Helper()

	want := readFile(t, filepath.Join("testdata", path))
	if normalizeNewlines(generated) != normalizeNewlines(want) {
		t.Fatalf("generated Go source differs from %s\nwant:\n%s\ngot:\n%s", path, want, generated)
	}
}

func assertGeneratedPackageCompiles(t *testing.T, source string) {
	t.Helper()

	dir := t.TempDir()
	if err := os.WriteFile(filepath.Join(dir, "go.mod"), []byte("module example.com/generated\n\ngo 1.22\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	if err := os.WriteFile(filepath.Join(dir, "types.gen.go"), []byte(source), 0o644); err != nil {
		t.Fatal(err)
	}

	cmd := exec.Command("go", "test", "./...")
	cmd.Dir = dir
	output, err := cmd.CombinedOutput()
	if err != nil {
		t.Fatalf("generated package does not compile: %v\n%s\nsource:\n%s", err, string(output), source)
	}
}

func assertUnsupportedDiagnostic(t *testing.T, diagnostics projector.Diagnostics, pointer, message string) {
	t.Helper()

	for _, d := range diagnostics {
		if d.Code == projector.CodeUnsupportedSchema && d.Pointer == pointer && strings.Contains(d.Message, message) {
			return
		}
	}
	t.Fatalf("expected unsupported schema diagnostic at %s containing %q, got %v", pointer, message, diagnostics)
}

func normalizeNewlines(value string) string {
	return strings.ReplaceAll(value, "\r\n", "\n")
}

func readFile(t *testing.T, path string) string {
	t.Helper()

	data, err := os.ReadFile(path)
	if err != nil {
		t.Fatal(err)
	}
	return string(data)
}
